/**
 * SQLite database service backed by Drizzle ORM.
 *
 * Lifecycle on app boot:
 *   1. Open the expo-sqlite connection with change listener enabled
 *      (required for `useLiveQuery` reactivity).
 *   2. Bridge dev DBs that were created by the pre-Drizzle schema runner so
 *      Drizzle's migrator does not try to re-apply `0000_initial`.
 *   3. Apply pending Drizzle migrations from the bundled folder.
 *   4. Seed the `hymns` table from the bundled JSON asset if empty.
 *
 * Subsequent launches are no-ops thanks to the memoized `initPromise` and the
 * `__drizzle_migrations` table that Drizzle maintains.
 */

import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/expo-sqlite";
import { migrate } from "drizzle-orm/expo-sqlite/migrator";
import * as SQLite from "expo-sqlite";

// Generated by `pnpm db:generate` — the SQL is inlined at bundle time by
// babel-plugin-inline-import.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated JS module without types
import drizzleMigrations from "../../../drizzle/migrations";

import hymnsSeed from "../../../assets/data/hymns.json";
import { DATABASE_CONFIG } from "./config";
import * as schema from "./schema";

type SeedHymn = {
  number: number;
  title: string;
  language: string | null;
  chorus?: string;
  verses: string[];
  content: string;
};

// Exported so dev tooling (expo-drizzle-studio-plugin) can attach to the
// same underlying SQLiteDatabase handle that Drizzle wraps.
export const sqliteDb = SQLite.openDatabaseSync(DATABASE_CONFIG.name, {
  enableChangeListener: true,
});

// Enable WAL once at startup. Cheap and idempotent.
sqliteDb.execSync("PRAGMA journal_mode = WAL;");

export const db = drizzle(sqliteDb, { schema });

let initPromise: Promise<void> | null = null;

export function initializeDatabase(): Promise<void> {
  if (!initPromise) {
    initPromise = doInitialize().catch((e) => {
      initPromise = null;
      throw e;
    });
  }
  return initPromise;
}

async function doInitialize(): Promise<void> {
  await bridgePreDrizzleDb();
  await migrate(db, drizzleMigrations);

  const [{ count }] = await db
    .select({ count: sql<number>`count(*)` })
    .from(schema.hymns);
  if (count === 0) await seed();
}

/**
 * Dev machines that opened the database under the pre-Drizzle schema runner
 * (PRs #6 + #7) already have a `hymns` table at the v2 shape but no
 * `__drizzle_migrations` table. Without this bridge, `migrate()` would
 * attempt to re-run `0000_initial.sql` and fail because the table exists.
 *
 * We create `__drizzle_migrations` and insert a marker row for the 0000
 * migration so Drizzle treats it as already applied. Production users will
 * never hit this path (no DB exists yet).
 */
async function bridgePreDrizzleDb(): Promise<void> {
  const hasHymns = await sqliteDb.getFirstAsync<{ name: string }>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='hymns'",
  );
  const hasDrizzleMeta = await sqliteDb.getFirstAsync<{ name: string }>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='__drizzle_migrations'",
  );
  if (!hasHymns || hasDrizzleMeta) return;

  await sqliteDb.execAsync(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id SERIAL PRIMARY KEY,
      hash text NOT NULL,
      created_at numeric
    );
  `);
  // Dev-only placeholder marker. Drizzle's migrator actually stores a
  // SHA-256 hash of each migration's SQL in `__drizzle_migrations.hash`;
  // we don't reproduce that hash here on purpose. The migrator advances by
  // `MAX(created_at)` to decide which entries are still pending, so as long
  // as the bridge row's `created_at` is greater than or equal to the journal
  // entry's `when` value, `migrate()` treats `0000_initial` as applied and
  // moves on. The hash column holds a human-readable tag so the row is
  // obvious if a dev opens the table in Drizzle Studio.
  //
  // Production users never hit this path — fresh installs go through the
  // normal `migrate()` flow which writes the real SHA-256 hash itself.
  const journal = (drizzleMigrations as { journal: { entries: Array<{ when: number }> } }).journal;
  const firstWhen = journal?.entries?.[0]?.when ?? Date.now();
  await sqliteDb.runAsync(
    "INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)",
    ["0000_initial (dev bridge placeholder)", firstWhen],
  );
}

async function seed(): Promise<void> {
  const data = hymnsSeed as ReadonlyArray<SeedHymn>;
  // Chunked inserts inside one transaction — much faster than per-row commits.
  const CHUNK = 100;
  await db.transaction(async (tx) => {
    for (let i = 0; i < data.length; i += CHUNK) {
      const slice = data.slice(i, i + CHUNK).map((hymn) => ({
        title: hymn.title,
        number: hymn.number,
        language: hymn.language,
        content: hymn.content,
        verses: JSON.stringify(hymn.verses),
        chorus: hymn.chorus ?? null,
      }));
      await tx.insert(schema.hymns).values(slice);
    }
  });
}
