-- FTS5 virtual table backing full-text search across hymn titles and content.
--
-- Hand-authored — drizzle-kit cannot model SQLite virtual tables, so this
-- migration is not regenerated by `pnpm db:generate`. Update the schema
-- snapshot manually if you add columns. See `schema.ts` for the note.
--
-- Tokenizer: `unicode61 remove_diacritics 2` strips combining accents so
-- queries match across Latin-accented text (Yoruba é/ô, French/Portuguese).
-- Non-Latin scripts (e.g. Igbo n-gba) are best-effort; the repository falls
-- back to `LIKE` when FTS5 returns zero rows on a non-ASCII query.
--
-- Stored as an external-content virtual table so the underlying `hymns`
-- table remains the source of truth and writes only need to fire delete /
-- insert into the FTS table via triggers.

CREATE VIRTUAL TABLE IF NOT EXISTS hymns_fts USING fts5(
  title,
  content,
  content='hymns',
  content_rowid='id',
  tokenize='unicode61 remove_diacritics 2'
);
--> statement-breakpoint
-- External-content FTS5's built-in `rebuild` command reads directly from the
-- content table and repopulates the index; unlike an INSERT ... SELECT this
-- is safe to run when `hymns_fts` already has rows (e.g. on a DB where the
-- vtable was created earlier but this migration re-runs without a fresh
-- install). No duplicate rowids can result.
INSERT INTO hymns_fts(hymns_fts) VALUES('rebuild');
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS hymns_ai AFTER INSERT ON hymns BEGIN
  INSERT INTO hymns_fts(rowid, title, content) VALUES (new.id, new.title, new.content);
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS hymns_ad AFTER DELETE ON hymns BEGIN
  INSERT INTO hymns_fts(hymns_fts, rowid, title, content) VALUES('delete', old.id, old.title, old.content);
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS hymns_au AFTER UPDATE ON hymns BEGIN
  INSERT INTO hymns_fts(hymns_fts, rowid, title, content) VALUES('delete', old.id, old.title, old.content);
  INSERT INTO hymns_fts(rowid, title, content) VALUES (new.id, new.title, new.content);
END;
